language: cpp

before_install:
    - sudo apt-get install -y python-software-properties
    - sudo add-apt-repository -y ppa:kalakris/cmake
    - sudo apt-get update -y
    - sudo apt-get install -y cmake valgrind libegl1-mesa-dev libgles2-mesa-dev libx11-dev libwayland-dev libbsd-dev

script:
  - ctest -VV --output-on-failure -S .magnum.ctest