install:
    - sudo apt-get install -y python-software-properties
    - sudo add-apt-repository -y ppa:george-edison55/precise-backports
    - sudo apt-get update -y
    - sudo apt-get install -y cmake cmake-data valgrind

script:
  - ctest -VV --output-on-failure -S CTestRun.cmake