###############################################################################
# libKD
# zlib/libpng License
###############################################################################
# Copyright (c) 2014-2015 Kevin Schmidt
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
# 1. The origin of this software must not be misrepresented; you must not
#    claim that you wrote the original software. If you use this software
#    in a product, an acknowledgment in the product documentation would be
#    appreciated but is not required.
# 2. Altered source versions must be plainly marked as such, and must not be
#    misrepresented as being the original software.
# 3. This notice may not be removed or altered from any source distribution.
###############################################################################

language: c

compiler:
  - gcc
  - clang

before_install:
  - if [ "$CC" = "gcc" ]; then export CC=gcc-4.9 && export CXX=g++-4.9; fi
  - if [ "$CC" = "clang" ]; then export CC=clang-3.5 && export CXX=clang++-3.5; fi
  - sudo apt-get purge --auto-remove gcc clang
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - if [ "$CC" = "clang-3.5" ]; then sudo apt-add-repository -y "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main"; fi
  - if [ "$CC" = "clang-3.5" ]; then wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -; fi
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq cmake
  - if [ "$CC" = "gcc-4.9" ]; then sudo apt-get install -qq gcc-4.9 g++-4.9 lcov; fi
  - if [ "$CC" = "gcc-4.9" ]; then wget -nc --no-check-certificate http://downloads.sourceforge.net/ltp/lcov-1.11.tar.gz && tar xzf lcov-1.11.tar.gz; fi
  - if [ "$CC" = "gcc-4.9" ]; then cd lcov-1.11 && make && sudo make install && cd ..; fi
  - if [ "$CC" = "gcc-4.9" ]; then gem install coveralls-lcov; fi
  - if [ "$CC" = "clang-3.5" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.5; fi
  - sudo apt-get install -qq libegl1-mesa-dev libgles2-mesa-dev libx11-dev libwayland-dev libbsd-dev

script:
  - ctest -V --output-on-failure -S .travis.ctest

after_success:
  - if [ "$CC" = "gcc-4.9" ]; then lcov --gcov-tool gcov-4.9 --compat-libtool --directory build --capture --output-file=coverage.info; fi
  - if [ "$CC" = "gcc-4.9" ]; then lcov --remove coverage.info 'distribution/*' 'examples/*' 'sourcecode/thirdparty/*' 'tests/*' 'cov-int/*' 'CMakeFiles/*' '/usr*' -o coverage.info; fi
  - if [ "$CC" = "gcc-4.9" ]; then coveralls-lcov coverage.info; fi

notifications:
  email:
    on_success: change
    on_failure: always

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Lo6vQDjM1B/BNAhTSphPCEbKxc7uaxOmg8GE+k94tVj4cZuzwvZb8YN8w6FCaHL/D8Vc+TIVAoBRBEGZ9J+VE02kK86kiN8ftcBevF5rtuDNyc4b7yohfpkdfIAe0IJxN76J5mLlwVvlGMPDkDMyPgwNQdSPQpa+HAvwK/kSOJw="

addons:
  coverity_scan:
    project:
      name: "h-s-c/libKD"
    notification_email: h-s-c@users.noreply.github.com
    build_command_prepend: "cmake -DCMAKE_BUILD_TYPE=Debug -DKD_BUILD_TESTS=On -DKD_BUILD_COVERAGE=On ."
    build_command:   "cmake --build . --config Debug"
    branch_pattern: coverity