language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env:
        - secure: "Lo6vQDjM1B/BNAhTSphPCEbKxc7uaxOmg8GE+k94tVj4cZuzwvZb8YN8w6FCaHL/D8Vc+TIVAoBRBEGZ9J+VE02kK86kiN8ftcBevF5rtuDNyc4b7yohfpkdfIAe0IJxN76J5mLlwVvlGMPDkDMyPgwNQdSPQpa+HAvwK/kSOJw="
        - COVERITY_SCAN_PROJECT_NAME="h-s-c/libKD"
        - COVERITY_SCAN_NOTIFICATION_EMAIL="h-s-c@users.noreply.github.com"
        - COVERITY_SCAN_BRANCH_PATTERN="coverity"
        - COVERITY_SCAN_BUILD_COMMAND="python ci-tools/run_ctest.py"
      install: python ci-tools/install_cmake.py  
      script:
        - if [ "$TRAVIS_BRANCH" = "coverity" ]; then 
            curl -s "https://scan.coverity.com/scripts/travisci_build_coverity_scan.sh" | /bin/bash;
          else true; fi;

    - os: linux
      compiler: gcc
      dist: precise
      sudo: required
      deploy:
        provider: packagecloud
        dist: "ubuntu/precise"
        repository: "libKD"
        username: "h-s-c"
        token:
          secure: "q55rWSAf5bU/WpC0l8SVS/F0UvGLvFBmn7TVZJ922Yz2nTswxojib9eFhbEds63LprN3/G1kE7VnUE/GygEpbw/z3shWnZIsymWfK18VwLIJZlcOUEyaFrmJwBbN742lkPxENObQjYrSuOSEA46ztcurXyRVsCTIzYvcbdveLW4="
        skip_cleanup: true
        on:
          branch: release
          tags: true
      install: python ci-tools/install_cmake.py  
      script:
        - if [ "$TRAVIS_TAG" ]; then 
            python ci-tools/run_cpack.py;
          else true; fi;

    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      deploy:
        provider: packagecloud
        dist: "ubuntu/trusty"
        repository: "libKD"
        username: "h-s-c"
        token:
          secure: "q55rWSAf5bU/WpC0l8SVS/F0UvGLvFBmn7TVZJ922Yz2nTswxojib9eFhbEds63LprN3/G1kE7VnUE/GygEpbw/z3shWnZIsymWfK18VwLIJZlcOUEyaFrmJwBbN742lkPxENObQjYrSuOSEA46ztcurXyRVsCTIzYvcbdveLW4="
        skip_cleanup: true
        on:
          branch: release
          tags: true
      install: python ci-tools/install_cmake.py  
      script:
        - if [ "$TRAVIS_TAG" ]; then 
            python ci-tools/run_cpack.py;
          else true; fi;

    - os: linux
      compiler: gcc-6
      dist: precise
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-6', 'valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: linux
      compiler: gcc-5
      dist: precise
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-5', 'valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: linux
      compiler: gcc-4.9
      dist: precise
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.9', 'valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: linux
      compiler: gcc-4.8
      dist: precise
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.8', 'valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: linux
      compiler: gcc-4.7
      dist: precise
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.7', 'valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: linux
      compiler: gcc-4.6
      dist: precise
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gcc-4.6', 'valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: linux
      compiler: clang-3.9
      dist: precise
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
          packages: ['clang-3.9', 'llvm-3.9', 'valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: linux
      compiler: clang-3.8
      dist: precise
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
          packages: ['clang-3.8', 'llvm-3.8', 'valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: linux
      compiler: clang-3.7
      dist: precise
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7', 'llvm-3.7', 'valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: linux
      compiler: clang-3.6
      dist: precise
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6', 'george-edison55-precise-backports']
          packages: ['clang-3.6', 'llvm-3.6', 'valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: linux
      compiler: clang-3.5
      dist: precise
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5', 'llvm-3.5', 'valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: linux
      compiler: icc
      dist: precise
      sudo: required
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['valgrind']
      install: python ci-tools/install_cmake.py && python ci-tools/install_icc.py
      before_script: source ci-tools/icc/bin/compilervars.sh intel64
      script: python ci-tools/run_ctest.py

    - os: osx
      compiler: clang
      osx_image: xcode7.3
      install: ['brew update', 'brew install valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: osx
      compiler: clang
      osx_image: xcode7.2
      install: ['brew update', 'brew install valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: osx
      compiler: clang
      osx_image: xcode7.1
      install: ['brew update', 'brew install valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: osx
      compiler: clang
      osx_image: xcode7
      install: ['brew update', 'brew install valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: osx
      compiler: clang
      osx_image: xcode6.4
      before_install:
        - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)" < /dev/null
        - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null
      install: ['brew update', 'brew install valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: osx
      compiler: clang
      osx_image: beta-xcode6.3
      install: ['brew update', 'brew install valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: osx
      compiler: clang
      osx_image: beta-xcode6.2
      install: ['brew update', 'brew install valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

    - os: osx
      compiler: clang
      osx_image: xcode6.1
      install: ['brew update', 'brew install valgrind']
      install: python ci-tools/install_cmake.py   
      script: python ci-tools/run_ctest.py

  allow_failures:
    - compiler: gcc-6       # Upstream Travis
    - compiler: clang-3.9   # Testing
    - compiler: clang-3.8   # Upstream LLVM
    - compiler: clang-3.7   # Upstream LLVM
    - compiler: icc         # Unstable