###############################################################################
# libKD
# zlib/libpng License
###############################################################################
# Copyright (c) 2014-2015 Kevin Schmidt
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
# 1. The origin of this software must not be misrepresented; you must not
#    claim that you wrote the original software. If you use this software
#    in a product, an acknowledgment in the product documentation would be
#    appreciated but is not required.
# 2. Altered source versions must be plainly marked as such, and must not be
#    misrepresented as being the original software.
# 3. This notice may not be removed or altered from any source distribution.
###############################################################################

sudo: false

language: c

compiler:
  - gcc-5
  - gcc-4.9
  - gcc-4.8
  - gcc-4.7
  - clang-3.7
  - clang-3.6

cache:
  - apt: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise-3.6
      - kalakris-cmake
    packages:
      - gcc-5
      - g++-5
      - gcc-4.9
      - g++-4.9
      - gcc-4.8
      - g++-4.8
      - gcc-4.7
      - g++-4.7
      - clang-3.7
      - llvm-3.7
      - clang-3.6
      - llvm-3.6
      - cmake
      - valgrind
      - libegl1-mesa-dev
      - libgles2-mesa-dev
      - libx11-dev
      - libbsd-dev

install:
  - echo -e "#!/bin/bash\n exec llvm-cov-3.7 gcov \"$@\"" > llvm-gcov-3.7
  - chmod +x llvm-gcov-3.7

script:
  - ctest -VV --output-on-failure -S .travis.ctest