###############################################################################
# libKD
# zlib/libpng License
###############################################################################
# Copyright (c) 2014-2015 Kevin Schmidt
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
# 1. The origin of this software must not be misrepresented; you must not
#    claim that you wrote the original software. If you use this software
#    in a product, an acknowledgment in the product documentation would be
#    appreciated but is not required.
# 2. Altered source versions must be plainly marked as such, and must not be
#    misrepresented as being the original software.
# 3. This notice may not be removed or altered from any source distribution.
###############################################################################

language: c

matrix:
  allow_failures:
    - os: osx

  include:
    - os: osx
      compiler: clang
      osx_image: xcode7.3

    - os: osx
      compiler: clang
      osx_image: xcode7.2

    - os: osx
      compiler: clang
      osx_image: xcode7.1

    - os: osx
      compiler: clang
      osx_image: xcode7

    - os: osx
      compiler: clang
      osx_image: xcode6.4

    - os: osx
      compiler: clang
      osx_image: xcode6.3

    - os: osx
      compiler: clang
      osx_image: xcode6.2

    - os: osx
      compiler: clang

    - os: osx
      compiler: gcc-6
      before_script: ['brew update', 'brew install homebrew/versions/gcc6']

    - os: osx
      compiler: gcc-5
      before_script: ['brew update', 'brew install homebrew/versions/gcc5']

    - os: osx
      compiler: gcc-4.9
      before_script: ['brew update', 'brew install homebrew/versions/gcc49']

    - os: osx
      compiler: gcc-4.8
      before_script: ['brew update', 'brew install homebrew/versions/gcc48']

    - os: osx
      compiler: gcc-4.7
      before_script: ['brew update', 'brew install homebrew/versions/gcc47']

    - os: osx
      compiler: gcc-4.6
      before_script: ['brew update', 'brew install homebrew/versions/gcc46']

#   - os: linux
#     compiler: gcc-6
#     sudo: false
#     addons:
#       apt:
#         sources: ['ubuntu-toolchain-r-test', 'kalakris-cmake']
#         packages: ['gcc-6', 'cmake', 'valgrind']

    - os: linux
      compiler: gcc-5
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'kalakris-cmake']
          packages: ['gcc-5', 'cmake', 'valgrind']

    - os: linux
      compiler: gcc-4.9
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'kalakris-cmake']
          packages: ['gcc-4.9', 'cmake', 'valgrind']

    - os: linux
      compiler: gcc-4.8
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'kalakris-cmake']
          packages: ['gcc-4.8', 'cmake', 'valgrind']

    - os: linux
      compiler: gcc-4.7
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'kalakris-cmake']
          packages: ['gcc-4.7', 'cmake', 'valgrind']

    - os: linux
      compiler: gcc-4.6
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'kalakris-cmake']
          packages: ['gcc-4.6', 'cmake', 'valgrind']

    - os: linux
      compiler: clang-3.7
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7', 'kalakris-cmake']
          packages: ['clang-3.7', 'llvm-3.7', 'cmake', 'valgrind']

    - os: linux
      compiler: clang-3.6
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6', 'kalakris-cmake']
          packages: ['clang-3.6', 'llvm-3.6', 'cmake', 'valgrind']

    - os: linux
      compiler: clang-3.5
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5', 'kalakris-cmake']
          packages: ['clang-3.5', 'llvm-3.5', 'cmake', 'valgrind']

script:
  - ctest -VV --output-on-failure -S CTestRun.cmake