language: c
compiler:
  - gcc
#  - clang

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - if [ "$CC" = "gcc" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CC" = "gcc" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 90; fi
  - if [ "$CC" = "gcc" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90; fi
  - if [ "$CC" = "gcc" ]; then sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 90; fi
  - sudo apt-get install -qq cmake lcov
  - wget -nc --no-check-certificate http://downloads.sourceforge.net/ltp/lcov-1.11.tar.gz
  - tar xzf lcov-1.11.tar.gz
  - cd lcov-1.11 && make && sudo make install
  - cd ..
  - gem install coveralls-lcov

install:
  - sudo apt-get install -qq libegl1-mesa-dev libgles2-mesa-dev libx11-dev libwayland-dev libbsd-dev

before_script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -DWANT_COVERAGE=On .

script:
  - make -j 4
  - make test

after_success:
  - lcov --compat-libtool --directory . --capture --output-file=coverage.info
  - lcov --remove coverage.info 'distribution/*' 'examples/*' 'sourcecode/thirdparty/*' 'tests/*' 'cov-int/*' 'CMakeFiles/*' '/usr*' -o coverage.info
  - coveralls-lcov coverage.info

notifications:
  email:
    on_success: change
    on_failure: always

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Lo6vQDjM1B/BNAhTSphPCEbKxc7uaxOmg8GE+k94tVj4cZuzwvZb8YN8w6FCaHL/D8Vc+TIVAoBRBEGZ9J+VE02kK86kiN8ftcBevF5rtuDNyc4b7yohfpkdfIAe0IJxN76J5mLlwVvlGMPDkDMyPgwNQdSPQpa+HAvwK/kSOJw="

addons:
  coverity_scan:
    project:
      name: "h-s-c/libKD"
    notification_email: h-s-c@users.noreply.github.com
    build_command_prepend: "cmake ."
    build_command:   "make -j4"
    branch_pattern: master