###############################################################################
# libKD
# zlib/libpng License
###############################################################################
# Copyright (c) 2014-2015 Kevin Schmidt
#
# This software is provided 'as-is', without any express or implied
# warranty. In no event will the authors be held liable for any damages
# arising from the use of this software.
#
# Permission is granted to anyone to use this software for any purpose,
# including commercial applications, and to alter it and redistribute it
# freely, subject to the following restrictions:
#
# 1. The origin of this software must not be misrepresented; you must not
#    claim that you wrote the original software. If you use this software
#    in a product, an acknowledgment in the product documentation would be
#    appreciated but is not required.
# 2. Altered source versions must be plainly marked as such, and must not be
#    misrepresented as being the original software.
# 3. This notice may not be removed or altered from any source distribution.
###############################################################################

language: c

matrix:
  include:
    - os: linux
      compiler: gcc-6
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['gcc-6', 'cmake', 'cmake-data', 'valgrind', 'libubsan0', 'libasan0', 'libtsan0']

    - os: linux
      compiler: gcc-5
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['gcc-5', 'cmake', 'cmake-data', 'valgrind', 'libubsan0', 'libasan0', 'libtsan0']

    - os: linux
      compiler: gcc-4.9
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['gcc-4.9', 'cmake', 'cmake-data', 'valgrind', 'libubsan0', 'libasan0', 'libtsan0']

    - os: linux
      compiler: gcc-4.8
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['gcc-4.8', 'cmake', 'cmake-data', 'valgrind', 'libubsan0', 'libasan0', 'libtsan0']

    - os: linux
      compiler: gcc-4.7
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['gcc-4.7', 'cmake', 'cmake-data', 'valgrind', 'libubsan0', 'libasan0', 'libtsan0']

    - os: linux
      compiler: gcc-4.6
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['gcc-4.6', 'cmake', 'cmake-data', 'valgrind', 'libubsan0', 'libasan0', 'libtsan0']

    - os: linux
      compiler: clang-3.8
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise', 'george-edison55-precise-backports']
          packages: ['clang-3.8', 'llvm-3.8', 'cmake', 'cmake-data', 'valgrind', 'libubsan0', 'libasan0', 'libtsan0']

    - os: linux
      compiler: clang-3.7
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7', 'george-edison55-precise-backports']
          packages: ['clang-3.7', 'llvm-3.7', 'cmake', 'cmake-data', 'valgrind', 'libubsan0', 'libasan0', 'libtsan0']

    - os: linux
      compiler: clang-3.6
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6', 'george-edison55-precise-backports']
          packages: ['clang-3.6', 'llvm-3.6', 'cmake', 'cmake-data', 'valgrind', 'libubsan0', 'libasan0', 'libtsan0']

    - os: linux
      compiler: clang-3.5
      sudo: false
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5', 'george-edison55-precise-backports']
          packages: ['clang-3.5', 'llvm-3.5', 'cmake', 'cmake-data', 'valgrind', 'libubsan0', 'libasan0', 'libtsan0']

    - os: linux
      compiler: icc
      sudo: false
      before_install: ['wget -q -O /dev/stdout "https://raw.githubusercontent.com/nemequ/icc-travis/master/install-icc.sh" | /bin/sh']
      before_script: ['source ~/.bashrc']
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
          packages: ['cmake', 'cmake-data', 'valgrind']

    - os: osx
      compiler: clang
      osx_image: xcode7.3
      before_script: ['brew update', 'brew install cmake', 'brew install valgrind']

    - os: osx
      compiler: clang
      osx_image: xcode7.2
      before_script: ['brew update', 'brew install cmake', 'brew install valgrind']

    - os: osx
      compiler: clang
      osx_image: xcode7.1
      before_script: ['brew update', 'brew install cmake', 'brew install valgrind']

    - os: osx
      compiler: clang
      osx_image: xcode7
      before_script: ['brew update', 'brew install cmake', 'brew install valgrind']

    - os: osx
      compiler: clang
      osx_image: xcode6.4
      before_script: ['brew update', 'brew unlink cmake', 'brew install cmake', 'brew install valgrind']

    - os: osx
      compiler: clang
      osx_image: beta-xcode6.3
      before_script: ['brew update', 'brew unlink cmake', 'brew install cmake', 'brew install valgrind']

    - os: osx
      compiler: clang
      osx_image: beta-xcode6.2
      before_script: ['brew update', 'brew unlink cmake', 'brew install cmake', 'brew install valgrind']

    - os: osx
      compiler: clang
      osx_image: xcode6.1
      before_script: ['brew update', 'brew unlink cmake', 'brew install cmake', 'brew install valgrind']

  allow_failures:
    - compiler: gcc-6       # Upstream Travis
    - compiler: clang-3.8   # Upstream LLVM
    - compiler: clang-3.7   # Upstream LLVM
    - compiler: icc         # On me
    - osx_image: xcode6.4   # Upstream Travis

script:
  - ctest -VV --output-on-failure -S CTestRun.cmake