version: "{build}"

image:
- Visual Studio 2017
- Visual Studio 2015
- Visual Studio 2013

before_build:
  - cinst ninja wget opencppcoverage
  - refreshenv
  - wget --no-check-certificate -P include/EGL https://www.khronos.org/registry/egl/api/EGL/egl.h
  - wget --no-check-certificate -P include/EGL https://www.khronos.org/registry/egl/api/EGL/eglext.h
  - wget --no-check-certificate -P include/EGL https://www.khronos.org/registry/egl/api/EGL/eglplatform.h
  - wget --no-check-certificate -P include/KHR https://www.khronos.org/registry/egl/api/KHR/khrplatform.h

build_script:
  - git submodule update --init --recursive
  - python ci-tools/run_ctest.py