version: 0.1.{build}

environment:
  matrix:
    - CTEST_CMAKE_GENERATOR: Visual Studio 14 2015
    - CTEST_CMAKE_GENERATOR: Visual Studio 14 2015 Win64
    - CTEST_CMAKE_GENERATOR: Visual Studio 14 2015 ARM
    - CTEST_CMAKE_GENERATOR: Visual Studio 12 2013
    - CTEST_CMAKE_GENERATOR: Visual Studio 12 2013 Win64
    - CTEST_CMAKE_GENERATOR: Visual Studio 12 2013 ARM

before_build:
  - git submodule update --init --recursive --quiet
  - appveyor DownloadFile https://github.com/h-s-c/libKD/releases/download/v0.0/OpenCppCoverage.7z
  - 7z x OpenCppCoverage.7z > nul
  - set PATH=%cd%\OpenCppCoverage;%PATH%
  - python ci/install_cmake.py
  - set PATH=%cd%\ci\build\cmake\bin;%PATH%

build_script:
  - ctest -VV -S CTestRun.cmake