version: 0.1.{build}

environment:
  matrix:
    - CTEST_CMAKE_GENERATOR: Visual Studio 14 2015
    - CTEST_CMAKE_GENERATOR: Visual Studio 14 2015 Win64
    - CTEST_CMAKE_GENERATOR: Visual Studio 14 2015 ARM
    - CTEST_CMAKE_GENERATOR: Visual Studio 12 2013
    - CTEST_CMAKE_GENERATOR: Visual Studio 12 2013 Win64
    - CTEST_CMAKE_GENERATOR: Visual Studio 12 2013 ARM
    - CTEST_CMAKE_GENERATOR: Visual Studio 11 2012
    - CTEST_CMAKE_GENERATOR: Visual Studio 11 2012 Win64
    - CTEST_CMAKE_GENERATOR: Visual Studio 11 2012 ARM
    - CTEST_CMAKE_GENERATOR: Visual Studio 10 2010
    - CTEST_CMAKE_GENERATOR: Visual Studio 10 2010 Win64

matrix:
  allow_failures:
    - CTEST_CMAKE_GENERATOR: Visual Studio 14 2015 ARM
    - CTEST_CMAKE_GENERATOR: Visual Studio 12 2013 ARM
    - CTEST_CMAKE_GENERATOR: Visual Studio 11 2012
    - CTEST_CMAKE_GENERATOR: Visual Studio 11 2012 Win64
    - CTEST_CMAKE_GENERATOR: Visual Studio 11 2012 ARM
    - CTEST_CMAKE_GENERATOR: Visual Studio 10 2010
    - CTEST_CMAKE_GENERATOR: Visual Studio 10 2010 Win64

before_build:
  - git submodule update --init --recursive --quiet
  - appveyor DownloadFile https://opencppcoverage.codeplex.com/downloads/get/1539055
  - OpenCppCoverageSetup-x64-0.9.4.1.exe /verysilent /norestart

build_script:
  - ctest -VV --output-on-failure -S CTestRun.cmake