version: 0.1.{build}

environment:
  matrix:
    - CTEST_CMAKE_GENERATOR: Visual Studio 14 2015
    - CTEST_CMAKE_GENERATOR: Visual Studio 14 2015 Win64
    - CTEST_CMAKE_GENERATOR: Visual Studio 14 2015 ARM
    - CTEST_CMAKE_GENERATOR: Visual Studio 12 2013
    - CTEST_CMAKE_GENERATOR: Visual Studio 12 2013 Win64
    - CTEST_CMAKE_GENERATOR: Visual Studio 12 2013 ARM

before_build:
  - cinst install wget opencppcoverage
  - wget --no-check-certificate -P include/EGL https://www.khronos.org/registry/egl/api/EGL/egl.h
  - wget --no-check-certificate -P include/EGL https://www.khronos.org/registry/egl/api/EGL/eglext.h
  - wget --no-check-certificate -P include/EGL https://www.khronos.org/registry/egl/api/EGL/eglplatform.h
  - wget --no-check-certificate -P include/KHR https://www.khronos.org/registry/egl/api/KHR/khrplatform.h

build_script:
  - git submodule update --init --recursive
  - python ci-tools/run_ctest.py