version: 0.1.{build}

environment:
  CMAKE_BUILD_TYPE: Debug
  matrix:
  - CMAKE_GENERATOR: Visual Studio 14 2015
  - CMAKE_GENERATOR: Visual Studio 14 2015 Win64
  - CMAKE_GENERATOR: Visual Studio 12 2013
  - CMAKE_GENERATOR: Visual Studio 12 2013 Win64
  - CMAKE_GENERATOR: Visual Studio 11 2012
  - CMAKE_GENERATOR: Visual Studio 11 2012 Win64
  - CMAKE_GENERATOR: Visual Studio 10 2010
  - CMAKE_GENERATOR: Visual Studio 10 2010 Win64
  - CMAKE_GENERATOR: Visual Studio 9 2008
  - CMAKE_GENERATOR: Visual Studio 9 2008 Win64

matrix:
  allow_failures:
    - CMAKE_GENERATOR: Visual Studio 11 2012
    - CMAKE_GENERATOR: Visual Studio 11 2012 Win64
    - CMAKE_GENERATOR: Visual Studio 10 2010
    - CMAKE_GENERATOR: Visual Studio 10 2010 Win64
    - CMAKE_GENERATOR: Visual Studio 9 2008
    - CMAKE_GENERATOR: Visual Studio 9 2008 Win64

before_build:
  - git submodule update --init --recursive --quiet

build_script:
  - ctest -VV --output-on-failure -S CTestRun.cmake