version: 0.1.{build}

environment:
  matrix:
    - CTEST_CMAKE_GENERATOR: Visual Studio 14 2015
    - CTEST_CMAKE_GENERATOR: Visual Studio 14 2015 Win64
    - CTEST_CMAKE_GENERATOR: Visual Studio 14 2015 ARM
    - CTEST_CMAKE_GENERATOR: Visual Studio 12 2013
    - CTEST_CMAKE_GENERATOR: Visual Studio 12 2013 Win64
    - CTEST_CMAKE_GENERATOR: Visual Studio 12 2013 ARM

before_build:
  - appveyor DownloadFile https://github.com/h-s-c/ci-tools/releases/download/0.1/OpenCppCoverage.7z
  - 7z x OpenCppCoverage.7z > nul
  - set PATH=%cd%\OpenCppCoverage;%PATH%
  - wget -P include/EGL https://www.khronos.org/registry/egl/api/EGL/egl.h
  - wget -P include/EGL https://www.khronos.org/registry/egl/api/EGL/eglext.h
  - wget -P include/EGL https://www.khronos.org/registry/egl/api/EGL/eglplatform.h
  - wget -P include/KHR https://www.khronos.org/registry/egl/api/KHR/khrplatform.h
  
build_script:
  - git submodule update --init --recursive
  - python ci-tools/install_cmake.py
  - python ci-tools/run_ctest.py