version: 0.1.{build}

os: Visual Studio 2015
platform:
  - x64

build_script:
- cmd: >-
    git submodule update --init --recursive --quiet

    set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%

    ctest -VV --output-on-failure -S CTestRun.cmake